name: brainhack-jb-env
channels:
  - default
  - conda-forge
dependencies:
  - python=3.10.*
  - pip
  - git
  - geopandas
  - ghp-import
  - jupytext
  - pandas
  - pytest
  - pip:
    - jupyter-book
    - osfclient
    - rich
    - black
    - requests
    - ruamel.yaml
    - cffconvert
    - plotly
    - flake8
