name: brainhack-jb-env
channels:
  - default
  - conda-forge
dependencies:
  - python=3.8.*
  - pip
  - git
  - bokeh=2.2.*
  - geopandas=0.8.*
  - ghp-import==1.0.1
  - jupytext=1.8.*
  - matplotlib==3.3.4
  - nbval
  - pandas>=1.1.*
  - pyshp==2.1.3
  - pytest
  - sphinx=3.5.1
  - pip:
    - jupyter-book==0.11.3
    - osfclient>=0.0.4
